name: "PR Metadata Action"
description: "A versatile GitHub Action event handler"
inputs:
  context:
    description: "The GitHub context object. Values of this object deduce the bot's next action."
    required: true
  debug:
    description: "An optional flag for additional logging within the action script."
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
